sudo: false
cache:
  directories:
  - "$HOME/.sbt/0.13/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.nvm"
language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
env:
  global:
  - TRAVIS_NODE_VERSION="4"
  - CATS_BOT_BUILD=true
  - secure: fvsbemzPxSEliATwzcnkzbxtZH5zjcjJhxzfvkRNPQNSXG+HGXiNTkkBpYKLTwr6ZQ9E7julMVC4P7Quc7lBSGGkoJBosSIJeLxyvD9AwRHjlkOPJkkVbDBsQ6CNwh6jOX/vlEgcJ8b5QmxVU/nD3OPsLjLVEXUfck95Zeh9IxVfUEE0+otfF8UQ1My48p9/Xg6VxzGRHQ3ZXVG8qIIOliPp9/DSKeiecKvxDscbHPG5/6ZI+NnEEAX5XahkF/0AEodg5NOcjZ9XMW1V0AX6/x34h+jj6tii6y4D6WQrbQRDP+/7kAlvWBF46RzOndep8QAkOTsgdq0iRkP5HOTF2wgSo7Hq+O8E67rDb+DGU0qV8TOXCpNrVyW+x1Qkg6k+Hb4GOsv/k1UdNoydp8FehtgLsIwHM9g1VO0Mx/aeIB/95DPQz2lpK0k1S9Zt6p4UUfUiGuFdIyskRre8wwuwnO1CJBIQmb7n184M9VG/94p3v2dI3fariHrcW8VplPnmcCVlAjUjbPwlPCrkP7G9ZuUJa53KulP5mHu22ilSgyoAzfFaPuX0wO3Wm9mGiIIb5i52pCLlVZZhv6xrbu2+pEwbRmuTUDtDIqqADZet97RqYmPcijZV6cWJhGBDDFsid0rHexOQzMO2sG/wddu46MQyjEbPsPf4surxwrALQV8=
  - secure: HYINV6v4wRz72OdRLvqjR1MgPejA+5kzL6DxGSU1k5b2hQbyKFgtwcGXYhOGj2PAZ+2ToE4NIf9i9UiVVjsRzve+at7E6ZtUDVijfUk/4IEF0V+X7K21RKEM+LhhKVp3n2wPZuRt11umia0VA8enEnpXbDZescpVmcFHHjvrZndFcLkiaPZcPIZ3rFWCK3VrEk5LYep5igM9fo4Ko8buaRPguRPGdVZqEnMS9GMvmaKy7pK7RtMI6OyGpBukugJoqsShKbt+yWLDbpDmRCdXEYSvEGvwRpQSk1Fgk8Uv4LDgSGKsWXqKdVbcXQxI5BtJO1T3oeb9ruQj5qx0NXI8beky8+aBQySaeU5NnbSMBMdEDJowtwTqejy4TX4OAAy6Xu/p1Vh2yMGDEBIsPmS3FzKsAShgf13+WyAufCjB9jnGBV9Z/k/PAZjK9GmnRqNlzAMgcY9c5incrKGMHf9AQM36lr4eHRJgEfi9mR1xwy7V4JgkQDoDdAI582kP47RTkY8d2ZqVhss7adcVDAYiBbcsr22fTuauxXhabxAUCnTenG5bAalp783IqO2cnYy/V2M5Ha7Yma4gA1VtzIt8oPIysNIwCuBjlbv0JS4oY6xKQwf+PwMOv4lX514ucoH1SPPkFB5qEsl+lr+Wprwr6G6C/zGkZk9Ymz7Vm0r/e2w=
script:
- scripts/travis-build.sh
install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install $TRAVIS_NODE_VERSION
