sudo: false

cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.nvm

language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

env:
  global:
  - TRAVIS_NODE_VERSION="4"
  - CATS_BOT_BUILD=true

before_install:
    - openssl aes-256-cbc -K $encrypted_78d67e04f03e_key -iv $encrypted_78d67e04f03e_iv -in scripts/bintray.tar.gz.enc -out bintray.tar.gz -d
    - tar xzf -C $HOME bintray.tar.gz

script:
  - scripts/travis-build.sh

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
